namespace: oitresearch-helmcharttemplate-dev

app:
  image:
    name: ghcr.io/southernmethodistuniversity/helm-chart-template
    tag: v0.0.1
  replicas: 1
  proxy: "http://webproxy.smu.edu:3128"
  no_proxy: ".smu.edu,10.0.0.0/8,129.119.0.0/16,104.150.0.0/16,172.29.0.0/16,172.30.0.0/16,.svc,.cluster.local,127.0.0.0/8,192.168.0.0/16"
  ingress:
    cname: helm-chart-template.oitresearch.smu.edu
    nginx:
      clientBodyTimeout: "600"
      proxyBodySize: "1024m"
      proxyConnectTimeout: "600"
      proxyReadSendTimeout: "3600"

splunk:
  index: oit_kub_acad_oitresearch
  secret: null